config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  resources :users
  get 'join' => 'users#new'

  get 'reviews' => 'users#reviews'

  get 'login' => 'sessions#new'

  get 'tampons' => 'products#tampons'

  get 'pads' => 'products#pads'

  get 'customize' => 'products#customize'

  get 'how_it_works' => 'users#how_it_works'

  get 'contact' => 'users#contact'
  delete 'logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
  resources :products
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  post 'users/thankyou' => 'users#thankyou'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items
  
  before_create :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :order_items

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  helper_method :current_order

  def current_order
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
end

end 

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
    redirect_to '/cart'

  end

    def update
      @order = current_order
      @order_item = @order.order_items.find(params[:id])
      @order_item.update_attributes(order_item_params)
      @order_items = @order.order_items
    end

    def destroy
      @order = current_order
      @order_item = @order.order_items.find(params[:id])
      @order_item.destroy
      @order_items = @order.order_items
      redirect_to '/cart'
    end

private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new
 end

 def create
  user = User.find_by_email(params[:email])
  if user && user.authenticate(params[:password])
    session[:user_id] = user.id
    redirect_to root_path, notice: "logged in!"
  else
   flash.now.alert = "invalid login credentials"
   render "new"
  end
 end

 def destroy
   session[:user_id] = nil  
  redirect_to root_url, notice: "logged out!"
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
  @user = User.new user_params
  if @user.save
   redirect_to users_path
  else
   render 'new'
  end
 end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

 private
   def user_params
    params.require(:user).permit( :email, :password, :password_confirmation)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= order_item.product.name%></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote:true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: order_item.product %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item_path(order_item), method: :delete,  class: "btn btn-danger"  %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>

  </div>
</div>

app/views/carts/_cart_row/html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the product '#{order_item.product.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>

  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", products_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Big Red Dot" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet">

    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">

        <div class="logo">
          <li><%= link_to image_tag('BRDLogo41.png', size: "69x69" ), root_path %></li>
        </div>
         <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>

      <section class="top-bar-section">

        <!-- Right Nav Section -->
        <ul class="right">
        <li class="has-dropdown">
        <a href="#">Products</a>
          <ul class="dropdown">
              <li><%= link_to "Products", products_path %></li>
              <li class="active"><%= link_to "Tampons", tampons_path %></li>
              <li class="active"><%= link_to "Pads", pads_path %></li>
              <li class="active"><%= link_to "Customize", customize_path %></li>
            </ul>
          </li>


          <li class="divider"></li>
          <li class=""><%= link_to "How it Works", how_it_works_path %> </li>
          <li class="divider"></li>
          <li class=""><%= link_to "Reviews", reviews_path %></li>
          <li class="divider"></li>
          <li class=""><%= link_to "Join", join_path %></li>
          <li class="divider"></li>
          <li class="has-dropdown">
          <a href="#">Login</a>
            <ul class="dropdown">
                <li><% if current_user %>
                    <li> Hello, <%= current_user.email %> </li>
                    <li><%= link_to 'Logout', logout_path, method: :delete, data: {confirm: 'Are you sure?'} %></li>
                  <% else %>
                    <li><%= render 'sessions/form_login' %></li>
                  <% end %>
                </li>
              </ul>
            </li>


          <li class="divider"></li>
          <li class="cart-text navbar-right"><%= render 'layouts/cart_text' %></li>

        </ul>
        <ul class="social-icons">
          <li><a href="contact"><i class="fi-telephone"></i></a></li>
          <li><a href=""><i class="fi-social-linkedin"></i></a></li>
          <li><a href="https://twitter.com/BigRedDotCo"><i class="fi-social-twitter"></i></a></li>
          <li><a href="https://www.facebook.com/Big-Red-Dot-922522001116807/"><i class="fi-social-facebook"></i></a></li>
          <li><a href="https://instagram.com/bigreddotco/"><i class="fi-social-instagram"></i></a></li>
        </ul>





        <% flash.each do |name, message| %>
        <div class="flash-message flash-message-<%= name %>">
          <%= message %>
        </div>
        <% end %>







      </section>

    </nav>


    <%= yield %>

  </body>
</html>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
  alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.html.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/products/_product_row.html.erb
<div class="well <%= product.name%>">

    <div class="col-xs-8">
      <p><%= product.name %></small></p>
      <p><%= "absorbency: " + product.absorbency %></small></p>
      <p><%= product.quantity %></small></p>
    </div>


    <div class="col-xs-4">
      <%= form_for order_item do |f| %>
      <p class="text-right">Price: <span style="color: green"><%= number_to_currency product.price %></span></p>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/products/index.html.erb
<h3 class="text-center">Products for Sale</h3>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% for message in @user.errors.full_messages %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :address1 %>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %>
    <%= f.password_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone_number %>
    <%= f.password_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/contact.html.erb
<h1>Contact Us</h1>

<div class="contact">

<form class="form-horizontal" role="form" method="post" action="thankyou">
    <div class="form-group">
        <label for="name" class="col-sm-2 control-label">Name</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="name" name="name" placeholder="First & Last Name" value="">
        </div>
    </div>
    <div class="form-group">
        <label for="email" class="col-sm-2 control-label">Email</label>
        <div class="col-sm-10">
            <input type="email" class="form-control" id="email" name="email" placeholder="example@domain.com" value="">
        </div>
    </div>
    <div class="form-group">
        <label for="message" class="col-sm-2 control-label">Message</label>
        <div class="col-sm-10">
            <textarea class="form-control" rows="4" name="message"></textarea>
        </div>
    </div>
    <div class="form-group">
        <label for="human" class="col-sm-2 control-label">2 + 3 = ?</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="human" name="human" placeholder="Your Answer">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <input id="submit" name="submit" type="submit" value="Send" class="btn btn-primary">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
            <! Will be used to display an alert to the user>
        </div>
    </div>
</form>


</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/how_it_works.html.erb
<h1>How It Works</h1>

<div class = "about">
<p>The last thing a woman should worry about while on her period is the cost of her tampons. After all, cotton ball are dirt cheap; shouldn't your hygiene products be affordable too?
<br><br>
At Big Red Dot, we allow you to buy your female hygiene products at a much lower cost while at your discretion. Forget those awkwardly embarrassing moments of carrying a box of tampons or bag of female diapers around a drugstore. You better hope you don't run into your new flame. So save yourself a trip and 85% of the cost. Get your feminine needs delivered to your door each month for your time of the month.
<br><br>
And no candy included. We won't sabotage your waistline or wallet.
<br><br>

Keep Calm. And Save Face and Money.</p>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Your one stop shop for that time of the month!</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }
  </style>
</head>
<body>

<div class="container">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">

      <div class="item active">
        <img src=http://foodmatters.tv/images/articles/feminine-hygiene-product-manufacturing.jpg alt="Simple" width="460" height="345">
        <div class="carousel-caption">
          <h3>Simple</h3>
          <p>We deliver exactly what you want- nothing more, nothing less.</p>
        </div>
      </div>

      <div class="item">
        <img src="http://www.wholefoodsmagazine.com/sites/default/files/images/articles/2011/April/Large%20Image/Fem-Hygiene.jpg" alt="Affordable" width="460" height="345">
        <div class="carousel-caption">
          <h3>Affordable</h3>
          <p>Necessities shouldn't cost an arm and a leg! We ship free.</p>
        </div>
      </div>

      <div class="item">
        <%= image_tag('content_full_width_4_ps.png')%>
        <div class="carousel-caption">
          <h3>Discreet</h3>
          <p>Forget embarassing tampon runs. Our products are delivered to your door in discreet packaging.</p>
        </div>
      </div>

      <div class="item">
        <img src="https://c2.staticflickr.com/6/5126/5374200948_539b10fb1c_b.jpg" alt="Timely" width="460" height="345">
        <div class="carousel-caption">
          <h3>Timely</h3>
          <p>Never get caught with your pants down with our monthly subscription option.</p>
        </div>
      </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<div class = "join">
<%= render 'form' %>
</div>

app/views/users/reviews.html.erb
<h1>Reviews</h1>

app/views/users/show.html.erb
<div class="">
  Profile Page for <%= @user.email %>
</div>

app/views/users/thankyou.html.erb
<p>
  Thank you for your inquiry. We will get back to you within the next 24 hours.
</p>